const property = [
  {
    id: 1,
    owner: 1,
    status: 'available',
    price: 22500.55,
    state: 'lagos',
    city: 'oworonshoki',
    address: '2, ladipo street',
    type: 'bungalow',
    created_on: new Date(),
    image_url: 'https://pixabay.com/photos/portrait-woman-lady-coffee-bar-4246954/',
    ownerEmail: 'olu@gmail.com',
    ownerPhoneNumber: '08089876543',
  },
  // {
  //   id: 2,
  //   owner: 20,
  //   status: 'available',
  //   price: 22500.55,
  //   state: 'lagos',
  //   city: 'epe',
  //   address: '2, ladipo street',
  //   type: 'bungalow',
  //   created_on: new Date(),
  //   image_url: 'https://pixabay.com/photos/portrait-woman-lady-coffee-bar-4246954/',
  //   ownerEmail: 'olu@gmail.com',
  //   ownerPhoneNumber: '08089876543',
  // },
  // {
  //   id: 3,
  //   owner: 10,
  //   status: 'available',
  //   price: 22500.55,
  //   state: 'kwara',
  //   city: 'shabs',
  //   address: '2, ladipo street',
  //   type: 'duplex',
  //   created_on: new Date(),
  //   image_url: 'https://pixabay.com/photos/portrait-woman-lady-coffee-bar-4246954/',
  //   ownerEmail: 'olu@gmail.com',
  //   ownerPhoneNumber: '08089876543',
  // },
];

export default property;
