const users = [
  {
    id: 1,
    email: 'john@test.com',
    firstName: 'Peace',
    lastName: 'Olowo',
    password: '$2b$10$44HEDknkmYvqkCSPvL8CeevWL2XDCjHiYdEfJJmm1PqCEVUN1r3kO',
    phoneNumber: '08086180776',
    address: '2, ladipo street, oworo, lagos',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'kate@yahoo.com',
    firstName: 'Kate',
    lastName: 'Henshaw',
    password: 'password',
    confirmPassword: 'password',
    phoneNumber: '08086180775',
    address: '2, ladipo street, oworo, lagos',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'ola@mum.com',
    firstName: 'Ola',
    lastName: 'Paris',
    password: 'password',
    confirmPassword: 'password',
    phoneNumber: '08086180775',
    address: '2, ladipo street, oworo, lagos',
    isAdmin: true,
  },
  {
    id: 4,
    email: 'brubbeck@itagi.com',
    firstName: 'Brubbeck',
    lastName: 'Jone',
    password: '456',
    confirmPassword: '456',
    phoneNumber: '09086180775',
    address: '4, mesh street, maitama, abuja',
    isAdmin: true,
  },
  {
    id: 5,
    email: 'morris@gmail.com',
    firstName: 'Morris',
    lastName: 'Iwu',
    password: 'abc',
    confirmPassword: 'abc',
    phoneNumber: '08086180775',
    address: '2, aha street, oworo, lagos',
    isAdmin: false,
  },
  {
    id: 6,
    email: 'padd@gmail.com',
    firstName: 'Padd',
    lastName: 'Mouse',
    password: 'password',
    confirmPassword: 'password',
    phoneNumber: '08086180775',
    address: '2, ladipo street, oworo, lagos',
    isAdmin: true,
  },
];

export default users;
